### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by hleete-mwi** [Moesif/moesifapi-nodejs#29]
When using Typescript in a NextJS project, trying to initialize a moesif object results in a "pjson is not defined" error.

Typescript Version: 5.0
NextJS Version: 13.5.6
moesif-nodejs Version: 3.5.3

In an API route file, the goal is to create a moesifMiddleware object so that I can call updateUser and updateCompany on that object. When trying to import moesif from moesif-nodejs and create an object as seen below, it fails. 

```
import moesif from "moesif-nodejs";

const moesifMiddleware = moesif({
  applicationId: "SECRET",
});
```

⨯ node_modules/moesifapi/lib/configuration.js (6:0) @ pjson
 ⨯ ReferenceError: pjson is not defined
    at eval (webpack-internal:///(rsc)/./node_modules/moesifapi/lib/configuration.js:6:7)
    at (rsc)/./node_modules/moesifapi/lib/configuration.js (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/vendor-chunks/moesifapi.js:160:1)
    at __webpack_require__ (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/moesifapi/lib/index.js:6:21)
    at (rsc)/./node_modules/moesifapi/lib/index.js (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/vendor-chunks/moesifapi.js:170:1)
    at __webpack_require__ (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./app/api/stripe/register/[checkout_session_id]/route.ts:7:67)
    at (rsc)/./app/api/stripe/register/[checkout_session_id]/route.ts (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/app/api/stripe/register/[checkout_session_id]/route.js:182:1)
    at __webpack_require__ (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fstripe%2Fregister%2F%5Bcheckout_session_id%5D%2Froute&page=%2Fapi%2Fstripe%2Fregister%2F%5Bcheckout_session_id%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fstripe%2Fregister%2F%5Bcheckout_session_id%5D%2Froute.ts&appDir=%2FUsers%2Fhl%2F_DEV_%2Fyoudotcom%2Fapi-self-serve-portal%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2Fhl%2F_DEV_%2Fyoudotcom%2Fapi-self-serve-portal&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:16:156)
    at (rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fstripe%2Fregister%2F%5Bcheckout_session_id%5D%2Froute&page=%2Fapi%2Fstripe%2Fregister%2F%5Bcheckout_session_id%5D%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fstripe%2Fregister%2F%5Bcheckout_session_id%5D%2Froute.ts&appDir=%2FUsers%2Fhl%2F_DEV_%2Fyoudotcom%2Fapi-self-serve-portal%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2Fhl%2F_DEV_%2Fyoudotcom%2Fapi-self-serve-portal&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D! (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/app/api/stripe/register/[checkout_session_id]/route.js:172:1)
    at __webpack_require__ (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/app/api/stripe/register/[checkout_session_id]/route.js:202:39)
    at /Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/app/api/stripe/register/[checkout_session_id]/route.js:203:803
    at __webpack_require__.X (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/webpack-runtime.js:146:21)
    at /Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/app/api/stripe/register/[checkout_session_id]/route.js:203:47
    at Object.<anonymous> (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/.next/server/app/api/stripe/register/[checkout_session_id]/route.js:206:3)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19)
    at mod.require (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:103:18)
    at requirePage (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/node_modules/next/dist/server/require.js:109:84)
    at /Users/hl/_DEV_/youdotcom/api-self-serve-portal/node_modules/next/dist/server/load-components.js:59:84
    at async loadComponentsImpl (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/node_modules/next/dist/server/load-components.js:59:26)
    at async DevServer.findPageComponentsImpl (/Users/hl/_DEV_/youdotcom/api-self-serve-portal/node_modules/next/dist/server/next-server.js:439:36) {
  page: '/api/stripe/register/SECRET'
}

**Comment by xinghengwang** [comment]
this is fixed.
